config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reply/create'
  post 'reply/create'
  
  get 'reply/destroy'
  get 'reply/destroy/:id' => 'reply#destroy'

  
  
  root 'post#index'
  get 'post/index'

  get 'post/new'

  get 'post/create'
  post 'post/create'
  
  get 'post/update'
  post 'post/update/:id' =>'post#update'

  get 'post/edit'
  get 'post/edit/:id' => 'post#edit'

  get 'post/destroy'
  get 'post/destroy/:id' => 'post#destroy'

  get 'post/show'
  get 'post/show/:id' => 'post#show'
  
  get 'post/search'
  
  get 'likes/likes_toggle/:id' => "likes#likes_toggle"
  post 'likes/likes_toggle'
  

end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :replies
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    
    validates :title, presence: true
end

app/models/reply.rb
class Reply < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  has_many :replies
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def likes_toggle
        like = Like.find_by(user_id: current_user.id, post_id: params[:id])
        
        if like.nil?
            Like.create(user_id: current_user.id, post_id: params[:id])
            
            #@likes = Like.new
            #@likes.user_id = current_user
            #@likes.post_id = params[:id]
            #@likes.save
        else
            like.destroy
        end
        
        redirect_to :back
    end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @post = Post.all.reverse
  end

  def new
  end

  def create
    uploader = ImageUploader.new
    uploader.store!(params[:image])

    @post = Post.new
    @post.title = params[:input_title]
    @post.content = params[:input_content]
    @post.user_id = current_user.id
    @post.image = uploader.url
    @post.thumb = uploader.thumb.url
    @post.middle = uploader.middle.url
    @post.save
    
    redirect_to "/post/index"
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:input_title]
    @post.content = params[:input_content]
    @post.save
    
    redirect_to "/post/show/" + params[:id]
  end

  def edit
    @post =Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    
    if current_user.id == @post.user_id
      @post.destroy
      redirect_to "/post/index"
    else
      redirect_to "/post/index"
    end
    
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def search
    if params[:cate] =="1"
      @post = Post.where("title LIKE ?", "%#{params[:q]}%")
    elsif params[:cate] == "2"
      @post = Post.where("content LIKE ?", "%#{params[:q]}%")
    elsif params[:cate] == "3"
      @post = Post.where("title LIKE? OR content LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
    elsif params[:cate] == "4"
      @post = User.where("username LIKE ?", "%#{params[:q]}%").take.posts
   end
  end
end

app/controllers/reply_controller.rb
class ReplyController < ApplicationController
  before_action :authenticate_user!
  def create
    @reply = Reply.new
    @reply.content = params[:content]
    @reply.post_id = params[:post_id]
    @reply.user_id = current_user.id
    @reply.save
    
    redirect_to :back
  end

  def destroy
    @reply = Reply.find(params[:id])
    
    if current_user.id == @reply.user_id
      @reply.destroy
    end
     redirect_to :back
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <% if user_signed_in? %>
        <div><%= current_user.email %></div>
        <a href="/users/sign_out">로그아웃</a>
    <% else %>
        <a href="/users/sign_in">로그인</a>
    <% end %>
    <form class="form-inline my-2 my-lg-0" action="/post/search" method="get">
      <div class="form-group">
        <select name="cate" class="form-control" id="exampleFormControlSelect1">
          <option value="1">제목</option>
          <option value="2">내용</option>
          <option value="3">제목+내용</option>
          <option value="4">작성자</option>
        </select>
      </div>
      <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/post/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/post/edit.html.erb
<div class="container">
    <form action = "/post/update/<%=@post.id%>" method="post">
      <div class="form-group">
        <label for="exampleFormControlInput1">제목</label>
        <input name="input_title" value="<%=@post.title%>" type="text" class="form-control" id="exampleFormControlInput1" placeholder="제목 입력해라">
      </div>
    
      <div class="form-group">
        <label for="exampleFormControlTextarea1">내용</label>
        <textarea name="input_content" class="form-control" id="exampleFormControlTextarea1" rows="10"  placeholder="내용 입력해라"><%=@post.content%></textarea>
      </div>
        <button type="submit" class="btn btn-dark">수정</button>

    </form>

</div>

app/views/post/index.html.erb
<%= render "navbar" %>
<div class="container">
   <a href="/post/new">
    <button type="button" class="btn btn-secondary">글쓰기</button><hr>
   </a>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">작성시간</th>
        </tr>
      </thead>
      
      <tbody>
        <% @post.each do |p| %>
         <tr>
          <th scope="row"><%=p.id%></th>
          <td><a href="/post/show/<%=p.id%>"><%=p.title%></a></td>
          <td><%=p.user.username%></td>
          <td><%=p.created_at.to_s.split("+").first%></td>
         </tr>
        <% end %>
      </tbody>
    </table>
    
</div>

app/views/post/new.html.erb
<div class="container">
    <form action = "/post/create" method="post" enctype="multipart/form-data">
      <div class="form-group">
        <label for="exampleFormControlInput1">제목</label>
        <input name="input_title" type="text" class="form-control" id="exampleFormControlInput1" placeholder="제목 입력해라">
      </div>
    
      <div class="form-group">
        <label for="exampleFormControlTextarea1">내용</label>
        <textarea name="input_content" class="form-control" id="exampleFormControlTextarea1" rows="10"  placeholder="내용 입력해라"></textarea>
      </div>
      <input name="image" type="file" accept="image/*" >
        <button type="submit" class="btn btn-dark">저장</button>

    </form>

</div>

app/views/post/search.html.erb
<%= render "navbar" %>
<div class="container">
   <a href="/post/new">
    <button type="button" class="btn btn-secondary">글쓰기</button><hr>
   </a>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">작성시간</th>
        </tr>
      </thead>
      
      <tbody>
        <% @post.each do |p| %>
         <tr>
          <th scope="row"><%=p.id%></th>
          <td><a href="/post/show/<%=p.id%>"><%=p.title%></a></td>
          <td><%=p.user.username%></td>
          <td><%=p.created_at.to_s.split("+").first%></td>
         </tr>
        <% end %>
      </tbody>
    </table>
    
</div>

app/views/post/show.html.erb
<div class="container">
    <h1><%=@post.title%></h1><hr/>
    <div style="text-align:right;">
        <!--to_s:문자열로 변환,+기준으로 나눠서,첫번쨰-->
        <div><%=@post.created_at.to_s.split("+").first%>, <%=time_ago_in_words(@post.created_at)%> ago</div> 
        <div>User name : <%=@post.user.username%></div>
        <a href="/post/edit/<%=@post.id%>"><span class="badge badge-pill badge-success">수정</span></a>
        <a href="/post/destroy/<%=@post.id%>"><span class="badge badge-pill badge-danger">삭제</span></a>
        
        
        <div><%= @post.liked_users.size %>명이 좋아합니다.</div>
        <% if current_user.is_like?(@post) %>
            <a href="/likes/likes_toggle/<%=@post.id%>">좋아요 취소</a>
            <!--<#%= link_to "좋아요 취소", likes_likes_toggle_path(@post), method: "post" %>-->
        <% else %>
            <a href="/likes/likes_toggle/<%=@post.id%>">좋아요</a>
            <!--<#%= link_to "좋아요", likes_likes_toggle_path(@post), method: "post" %>-->
        <% end %>
     
    </div>
  
    
    <p><%= simple_format(@post.content)%></p>
    
    <% unless @post.image.nil? %>
        <%= image_tag @post.image, width: "600" %>
        <%= image_tag @post.thumb %>
        <%= image_tag @post.middle %>
    <%end%>
    ;
    
    <div style="text-align:right;">
        <a href="/post/index"><button type="button" class="btn btn-info">목록</button></a><hr>
    </div>
    
    <%@post.replies.each do |r| %>
        <%= r.user.username %> : <%=r.content%>
        <a href="/reply/destroy/<%=r.id%>"><span class="badge badge-pill badge-danger">삭제</span></a>
        <br>
    <%end%>
    
    
    <form action="/reply/create" method="post">
        <input name="post_id" value="<%=@post.id%>" hidden="true">
        <div class="row">
          <textarea name="content" class="form-control col-11" id="exampleFormControlTextarea1" rows="3"  placeholder="댓글작성"></textarea>
          <button type="submit" class="btn btn-dark">댓글 작성</button>
        </div>
        
    </form>    
</div>

app/views/post/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>

app/views/reply/create.html.erb
<h1>Reply#create</h1>
<p>Find me in app/views/reply/create.html.erb</p>

app/views/reply/destroy.html.erb
<h1>Reply#destroy</h1>
<p>Find me in app/views/reply/destroy.html.erb</p>